### DISCUSSION TITLE
Do something like a "double hardline" / two line breaks

### DISCUSSION THREAD

**Discussion by tfachmann** [topiary/topiary#993] [Q&A] [answered]
Take for example some `toml` code:

```toml
[dev-dependencies]
criterion = "0.4"
[ bench ]
name = "benchmark"
harness = false
```

Assume that the block `[dev-dependencies] ...` is named a `(table)`.

Is it possible to _force_ exactly two line breaks after `table`s? 

i.e.

```toml
[dev-dependencies]
criterion = "0.4"

[ bench ]
name = "benchmark"
harness = false
```

I know that it's possible to `(table) @allow_blank_line_before` such that an additional line break is allowed if the user provides it, however I want to make sure that it will format it to always be one more line break.
